site_name: MeteoNet's Documentation
theme:
  name: 'material'
  logo:
    icon: 'cloud'
repo_url: https://github.com/meteofrance/meteonet
repo_name: 'GitHub'

docs_dir: 'docs_src'
site_dir: 'docs'

plugins:
  - search
  - mkdocs-add-number-plugin:
      strict_mode: False
      order: 2
  - awesome-pages

markdown_extensions:
  - footnotes
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition
  - attr_list
  - mdx_math

extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
  - 'index.md'
  - 'getting-started.md'
  - 'install.md'
  - Data:
    - 'data/summary.md'
    - 'data/ground-observations.md'
    - 'data/rain-radar.md'
    - 'data/weather-models.md'
    - 'data/land-relief-masks.md'
  - 'glossary.md'
  - 'help.md'